// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1dFyneE-v13X7UfmByb8LIFsBHXEd9Pg',
    appId: '1:707544187649:web:82558733a9bdd69acbd100',
    messagingSenderId: '707544187649',
    projectId: 'tracking-your-habits-app',
    authDomain: 'tracking-your-habits-app.firebaseapp.com',
    storageBucket: 'tracking-your-habits-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbcslkwWDePHsfHrHv7T-mCxaIO8w4lC0',
    appId: '1:707544187649:android:e630861b39d958d1cbd100',
    messagingSenderId: '707544187649',
    projectId: 'tracking-your-habits-app',
    storageBucket: 'tracking-your-habits-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLGcwPExxwlr_FrM7U9k7drdiuI8cX2Ng',
    appId: '1:707544187649:ios:8c5a6e474d3d542dcbd100',
    messagingSenderId: '707544187649',
    projectId: 'tracking-your-habits-app',
    storageBucket: 'tracking-your-habits-app.firebasestorage.app',
    iosBundleId: 'com.example.trackingYourHabits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLGcwPExxwlr_FrM7U9k7drdiuI8cX2Ng',
    appId: '1:707544187649:ios:8c5a6e474d3d542dcbd100',
    messagingSenderId: '707544187649',
    projectId: 'tracking-your-habits-app',
    storageBucket: 'tracking-your-habits-app.firebasestorage.app',
    iosBundleId: 'com.example.trackingYourHabits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1dFyneE-v13X7UfmByb8LIFsBHXEd9Pg',
    appId: '1:707544187649:web:3f20e86364c5e892cbd100',
    messagingSenderId: '707544187649',
    projectId: 'tracking-your-habits-app',
    authDomain: 'tracking-your-habits-app.firebaseapp.com',
    storageBucket: 'tracking-your-habits-app.firebasestorage.app',
  );
}
