// Mocks generated by Mockito 5.4.4 from annotations
// in tracking_your_habits/test/viewmodels/habit_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tracking_your_habits/src/datasources/habit_datasource.dart'
    as _i2;
import 'package:tracking_your_habits/src/models/habit.dart' as _i4;
import 'package:tracking_your_habits/src/repositories/habit_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHabitDataSource_0 extends _i1.SmartFake
    implements _i2.HabitDataSource {
  _FakeHabitDataSource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HabitRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHabitRepository extends _i1.Mock implements _i3.HabitRepository {
  MockHabitRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HabitDataSource get dataSource => (super.noSuchMethod(
        Invocation.getter(#dataSource),
        returnValue: _FakeHabitDataSource_0(
          this,
          Invocation.getter(#dataSource),
        ),
      ) as _i2.HabitDataSource);

  @override
  List<_i4.Habit> getHabits(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getHabits,
          [userId],
        ),
        returnValue: <_i4.Habit>[],
      ) as List<_i4.Habit>);

  @override
  _i5.Future<void> addHabit(_i4.Habit? habit) => (super.noSuchMethod(
        Invocation.method(
          #addHabit,
          [habit],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateHabit(_i4.Habit? habit) => (super.noSuchMethod(
        Invocation.method(
          #updateHabit,
          [habit],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteHabit(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteHabit,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
